### PR TITLE
Fix "behavior" spelling

### LINKED ISSUE #4: Bug: Behaviour → Behavior
https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll#behavior

Some parts of the code this is named incorrectly which won't work. If the English dialect discrepancies irk you, a type alias should suffice for the enum. There's probably a fancy way to unify the option key name with the Row-level renaming bits that could accept both.

It may be better to not try to read the PureScript data model from the FFI in case those implementations change--using `print`/`parse` for the enum, may be preferred.

### PR DESCRIPTION
**Pull request by keijokapp**
Closes #4

### CODE REVIEW

**Review by garyb — APPROVED** [review]
I (British) made this kind of mistake so many times!

**Comment by toastal** [comment]
@garyb If it's any consolation, Erlang seamlessly supports both `behavior` and `behaviour` as keywords without acting like one of the spellings is more _correct_.

**Comment by keijokapp** [comment]
As I understand, the goal here is to mimic web standards as closely as possible and the standard says `behavior`. I don't speak neither English natively and don't have any preference aside from what the standard says. I don't think the effort and complexity of supporting both variants (and deviating from the standard by doing so) is warranted.

**Comment by toastal** [comment]
Agreed it's not worth it in the `Web` libraries as they're meant to follow specs. It's just an unfortunate part of programming that what is the same word but different spelling often isn't supported.

**Pull request merged**
